### PR TITLE
Fixing blog verification test

### PR DESCRIPTION
**Pull request by laheara143**
## Describe context / purpose for this PR
Verification of created blog test was not working.
## Issue link
https://cyberteamportal.atlassian.net/browse/D8-1621
## Link to MultiDev instance

http://md-{{ ticket number }}-accessmatch.pantheonsite.io

## Checklist for PR author
- [ ] I have checked that the PR is ready to be merged
- [ ] I have reviewed the DIFF and checked that the changes are as expected
- [ ] I have assigned myself or someone else to review the PR

### CODE REVIEW

**Comment by laheara143** [comment]
Issue with Github Testing is making all test fail

**Comment by laheara143** [comment]
Issue with page not loading, other tests are passing

**Comment by laheara143** [comment]
When I go to the homepage

**Review by jasperlieber — CHANGES_REQUESTED** [review]

**Comment by jasperlieber** [comment]
The main part of this PR was to test blog creation, and it's not working.  Jira ticket has been filed.  Closing this PR.  New work should be done once blog creation can be tested.

**Pull request closed without merging**
