### PR TITLE
D8-1086 -- remove "site under development" block

### PR DESCRIPTION
**Pull request by jasperlieber**
ready for review

### CODE REVIEW

**Comment by jasperlieber** [comment]
hold up!  i found that the cc-applications page needs to have the 2nd Submit button removed, doing that now

**Comment by a-pasquale** [comment]
What is the issue with the submit button?

**Comment by jasperlieber** [comment]
I put details about the 2nd button on the jira ticket.  I thought the ask was to remove the second "Apply to selected items" button -- but perhaps that's incorrect.

**Comment by jasperlieber** [comment]
Ok, the two "Apply to selected items" buttons are fine.  Ready for review

**Pull request merged**
