### PR TITLE
Fix for changed date format

### PR DESCRIPTION
**Pull request by laheara143**
## Describe context / purpose for this PR
Fixing broken test
## Link to MultiDev instance

http://md-{{ ticket number }}-accessmatch.pantheonsite.io

## Checklist for PR author
- [ ] I have checked that the PR is ready to be merged
- [ ] I have reviewed the DIFF and checked that the changes are as expected
- [ ] I have assigned myself or someone else to review the PR

### CODE REVIEW

**Comment by laheara143** [comment]
I removed the broken line. The line was on the page but for some reason it fails

**Comment by a-pasquale** [comment]
Looks like the main branch is still passing. I think this might be because we just removed the brackets from around the date in the asp-theme branch and those views are on the other domains as well. Can we try just removing the brackets and see what happens?

**Comment by laheara143** [comment]
Should I fix asp testing?

**Comment by laheara143** [comment]
The tests are failing because the date has brackets but it should not have brackets

**Comment by laheara143** [comment]
The test fails due to not seeing "test-affinity-group" I followed the steps manually and it worked so I will look more into this later

**Comment by laheara143** [comment]
Creating on new branch due to there being too many conflicts

**Pull request closed without merging**
