### PR TITLE
add drupal_seamless_cilogon to composer

### PR DESCRIPTION
**Pull request by jasperlieber**
@a-pasquale  -- see the real work at https://github.com/access-ci-org/drupal_seamless_cilogon/pull/1

### CODE REVIEW

**Comment by jasperlieber** [comment]
hi @a-pasquale  -- the test fails with this:

```
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Required package "amp/drupal_seamless_cilogon" is not present in the lock file.
```

not immediately sure how to fix that

**Comment by a-pasquale** [comment]
Can you rename amp to asp? We would like to transition to the newer name.

Try composer update asp/drupal_seamless_cilogon. You’ll eventually need to commit both the composer.json and composer.lock files.

**Comment by jasperlieber** [comment]
hi @a-pasquale -- does the `drupal_seamless_cilogon` directory need to be added to this main repo?

I tried the following, but now don't know if i should do a `git rm --cached web/modules/custom/drupal_seamless_cilogon`:

```
amp3  07:10 PM ~/cyberteam_drupal/web/modules/custom 2027 | git add drupal_seamless_cilogon/
warning: adding embedded git repository: web/modules/custom/drupal_seamless_cilogon
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint:   git submodule add <url> web/modules/custom/drupal_seamless_cilogon
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint:   git rm --cached web/modules/custom/drupal_seamless_cilogon
hint: 
hint: See "git help submodule" for more information.
```

**Comment by a-pasquale** [comment]
composer should manage the directory. You do not need to add it with git.

**Comment by a-pasquale** [comment]
Superceded by PR #439

**Pull request closed without merging**
