### PR TITLE
CCMNet user registration form d8-2041

### PR DESCRIPTION
**Pull request by FloQuinn**
## Describe context / purpose for this PR
Config changes For CCMNet user registration form. Added CCMNet Role. …
…Permission changes on User Profile custom fields: field_region, access organization (plus add ccmnet role). Current Occupation label is now 'Job Title', add ccmnet role.

## Issue link
https://cyberteamportal.atlassian.net/browse/D8-2041

## Any other related PRs?
https://github.com/necyberteam/access/pull/203

## Link to MultiDev instance

http://md-2041-accessmatch.pantheonsite.io

## Checklist for PR author
- [ ] I have checked that the PR is ready to be merged
- [ ] I have reviewed the DIFF and checked that the changes are as expected
- [ ] I have assigned myself or someone else to review the PR

### CODE REVIEW

**Comment by FloQuinn** [comment]
@a-pasquale I think this is complete.  The trouble is that on the md-2041, when I change to ccmnet domain, the front page is not correct.   Changing to other domains works. 
/user/register/ccmnet is good though.

**Comment by a-pasquale** [comment]
> @a-pasquale I think this is complete. The trouble is that on the md-2041, when I change to ccmnet domain, the front page is not correct. Changing to other domains works. I did not have that problem on my codespace. I can't create a user because of the captcha. Is there something I can do to remove that so we can test the user register? /user/register/ is correct.

I registered the domain with reCaptcha. You can fix the front page issue by clearing the cache.

**Comment by FloQuinn** [comment]
@a-pasquale I got halfway through a commit with the most recent requrested changes and ran into branch problems. it's not ready now, will update.

**Comment by FloQuinn** [comment]
@a-pasquale  This looks good now up on md-2041

**Pull request merged**
