### PR TITLE
Adding in changes to AG request form

### PR DESCRIPTION
**Pull request by laheara143**
## Describe context / purpose for this PR

Adding in changes to the Affinity Group Request Form to improve the flow.
Changes include:
Conditional changes
Text
Format

## Issue link
https://cyberteamportal.atlassian.net/browse/D8-1804
## Any other related PRs?

#916

## Link to MultiDev instance

http://md-1804R-accessmatch.pantheonsite.io

## Checklist for PR author
- [ ] I have checked that the PR is ready to be merged
- [x] I have reviewed the DIFF and checked that the changes are as expected
- [x] I have assigned myself or someone else to review the PR

### CODE REVIEW

**Comment by laheara143** [comment]
This needs to be reviewed especillay for number 3 since the positioning is a little off
3.Add a Checkbox field: Do you have a logo or image? Yes or no. The logo field should be conditional, required if the answer to this question is yes.
Text for cider resources needs to be fixed as well.
6.(add bold text) If you are an ACCESS RP, select one (or more) related CiDeR resources

**Comment by laheara143** [comment]
Test are failing due to text change should I fix those in this PR?

**Comment by a-pasquale** [comment]
> Test are failing due to text change should I fix those in this PR?

Yes, please!

**Comment by a-pasquale** [comment]
Please recreate this branch without a capital letter. Pantheon will not create the md- branch with uppercase characters.

**Pull request closed without merging**
