### PR TITLE
Adding in test for uncovered routes

### PR DESCRIPTION
**Pull request by laheara143**
## Describe context / purpose for this PR
Adding in behat testing for uncovered areas of ASP
## Issue link
https://cyberteamportal.atlassian.net/browse/D8-1825
## Link to MultiDev instance

http://md-{{ ticket number }}-accessmatch.pantheonsite.io

## Checklist for PR author
- [x] I have checked that the PR is ready to be merged
- [x] I have reviewed the DIFF and checked that the changes are as expected
- [x] I have assigned myself or someone else to review the PR

### CODE REVIEW

**Comment by laheara143** [comment]
A couple of tests were added in to cover routes that do not currently have tests covering them. All tests passed!

**Comment by a-pasquale** [comment]
This is testing for an existing CI Link which should not be present in a sanitized database.

**Comment by laheara143** [comment]
Fix CI Links test to test for correct title

**Comment by laheara143** [comment]
CI Link is within amp_dev

**Pull request merged**
