### PR TITLE
D8 1164 Config changes so that "resources" replaced with "CI links"  including url routes

### PR DESCRIPTION
**Pull request by FloQuinn**
The term "resources" needs to be replaced by the new term, "CI Links" site-wide, including most url routes. 
This branch contains the config changes.  There will also be content changes made to the live site, including the footer menu and some of the buttons.   
Most of the changes are in the 'resource' webform.  We decided against changing the machine name of this webform, which would involve creating a new form and migrating all the existing resources to the new form.  We were able to use an alias instead.
Many of the changes are in one place for both Access and the rest of the portals.  Some are not, such as the resources view + card view.
Some spots affected by this change include resource list on affinity group individual page, on the tags page, on individual tag page, 
/resources -> /ci-links
/resources-card -> /ci-links-card
/form/resource-> /form/ci-link
/resource/8 -> /ci-link/8  (an individual resource numbered 8)

### CODE REVIEW

**Comment by jasperlieber** [comment]
and https://github.com/necyberteam/cyberteam_drupal/pull/521 should fix failing tests

**Comment by jasperlieber** [comment]
Knowledge Based contributions are also consider resources -- does this need checking too?

**Comment by jasperlieber** [comment]
(will let @a-pasquale close this)

**Comment by a-pasquale** [comment]
@jasperlieber the "Knowledge Base Contributions" in the community persona is currently the same as Resources/CI Links, but may someday expand to include pulling ask.ci contributions. We were anticipating this change to CI Links and tried to avoid using the term there.

@FloQuinn can you recreate this branch as an md- branch so we can easily test on Pantheon?

Thanks!

**Comment by a-pasquale** [comment]
Closing, superceded by md branch

**Pull request closed without merging**
