### PR TITLE
Behat jasper

### PR DESCRIPTION
**Pull request by jasperlieber**
removed some obsolete features, and added cyberteam-unathenticated directory containing my first feature test for News

### CODE REVIEW

**Comment by a-pasquale** [comment]
I think Scenario descriptions should be "Link to press release page displays Press Release"  or something similar.

**Review by protitude — COMMENTED** [review]
Is there a reason for creating a new folder for unauthenticated tests? Currently this won't be a part of the full behat run. I think it makes sense to keep it in the cyberteam folder with the @cyberteam tag, though you could add the additional @cyberteam-unauthenticated tag if there's a reason for splicing that out.

**Comment by jasperlieber** [comment]
> Is there a reason for creating a new folder for unauthenticated tests? Currently this won't be a part of the full behat run. I think it makes sense to keep it in the cyberteam folder with the @cyberteam tag, though you could add the additional @cyberteam-unauthenticated tag if there's a reason for splicing that out.

As a total n00b to behat, my intuition was that we might end up having many tests, and that it would be good to try to segment these into various categories via different folders.  Any thoughts about this?

**Comment by jasperlieber** [comment]
> I think Scenario descriptions should be "Link to press release page displays Press Release" or something similar.

Ok, thanks, I'll update those.

**Pull request merged**
