### PR TITLE
behat - add a "image should load" custom step

### PR DESCRIPTION
**Pull request by jasperlieber**
also added a homepage_logo.feature example use of it

### CODE REVIEW

**Comment by a-pasquale** [comment]
The selector should select the  element rather than the parent element.

**Comment by jasperlieber** [comment]
> The selector should select the  element rather than the parent element.

Hi @a-pasquale 

Do you mean within the custom step?  It's doing a `$page->findAll('css', $selector)`  and then loooking for an `img` within that element.  (Looks like there's a missing word of symbol in your sentence above, was it supposed to "should select the _child_ element"?)

Or do you mean that within `homepage_logo.feature`, I should look for `.logo` instead of `.navbar-brand` ?

**Comment by jasperlieber** [comment]
hi @a-pasquale  -- what do you think about an even more specfic custom step that looks like this:  `I should see an image with alt text "Campus Champions"`  It was easy to add, thought it might be nice to have this level of fine-tuning.

**Comment by a-pasquale** [comment]
Alt text test is fine as an additional test.

The selector should be on the image element, not the parent div. You should
be entering a selector like .logo.

**Comment by jasperlieber** [comment]
and i've update the homepage test to look for `.logo` (instead of parent)

**Pull request merged**
